MeetingRoomBooking/MeetingRoomBooking/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MeetingRoomBooking.DATA;
using MeetingRoomBooking.Models;
//using static MeetingRoomBooking.Models.Documents;

namespace MeetingRoomBooking.Controllers
{
    public class BookingController : Controller
    {
        // GET: Booking
        public ActionResult Index()
        {

            dbMeetingRoomBookingDataContext db = new dbMeetingRoomBookingDataContext();



            var model = new Documents();

            foreach(var rs in db.MAS_TIMEs)
            {
                Documents.CheckBox chk = new Documents.CheckBox();
                chk.Checked = false;
                chk.topic = rs.S_TIME + "-"+ rs.E_TIME;
                chk.id = rs.TMCODE;

                model.getchk.Add(chk);
            }

            foreach (var rs in db.MAS_DRINKs)
            {
                Documents.CheckBox chk = new Documents.CheckBox();
                chk.Checked = false;
                chk.topic = rs.NAME;
                chk.id = rs.TDCODE;

                model.drinkchk.Add(chk);
            }

            foreach (var rs in db.MAS_TOOLs)
            {
                Documents.CheckBox chk = new Documents.CheckBox();
                chk.Checked = false;
                chk.topic = rs.NAME;
                chk.id = rs.TLCODE;

                model.toolkchk.Add(chk);
            }


            return View(model);
        }



    }
}

MeetingRoomBooking/MeetingRoomBooking/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetingRoomBooking.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }
    }
}

MeetingRoomBooking/MeetingRoomBooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

               @* @Html.ActionLink("จองห้องประชุม ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("หน้าแรก", "Index", "Booking")</li>
                    <li>@Html.ActionLink("รายงาน", "Index", "Report")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MeetingRoomBooking/MeetingRoomBooking/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                </ul>

                @*<ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> รายงาน <b class="caret"></b></a>
                        <ul class="dropdown-menu multi-level">
                            <li class="dropdown-submenu">
                                    @Html.ActionLink("รายงาน สั่งงานช่าง ", "Report", "Ticket")
                                </li>
                                <li class="divider"></li>
                                <li class="dropdown-submenu">
                                    @Html.ActionLink("รายงาน อนุมัติเข้าอาคาร", "Report", "TicketApprove")
                                </li>
                        </ul>
                    </li>

                </ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>